notifications:
  email: false

sudo: false

language: rust

rust:
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly
  include:
    - os: osx
      rust: nightly

script:
  - RUST_BACKTRACE=1 cargo test --all --verbose

